version: "3.9"
-
services:

  db_production:
    image: postgres
    volumes:
      - uni_auction_production_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangoDB
      - POSTGRES_USER=djangoUSER
      - POSTGRES_PASSWORD=djangoPASS

  web_production:
    build: .
    command: gunicorn --bind 0.0.0.0:8888 auction_core.wsgi
    volumes:
      - .:/code
    ports:
      - "8889:8888"
    env_file:
      - .prod.env
    environment:
      - TAG=${TAG}
      - ENV=production
    depends_on:
      - db_production

volumes:
  uni_auction_production_postgres_data:
