version: "3.9"

services:

  db:
    image: postgres
    volumes:
      - uni_auction_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangoDB
      - POSTGRES_USER=djangoUSER
      - POSTGRES_PASSWORD=djangoPASS

  web:
    build: .
    entrypoint:
      - ./entrypoint.sh
    image: "uni_auction_${TAG}"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TAG=${TAG}
      - ENV=dev
    depends_on:
      - db

volumes:
  uni_auction_postgres_data:
