version: "3.9"

services:

  db_stage:
    image: postgres
    volumes:
      - uni_auction_stage_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangoDB
      - POSTGRES_USER=djangoUSER
      - POSTGRES_PASSWORD=djangoPASS

  web_stage:
    build: .
    command:
      - gunicorn --bind 0.0.0.0:8888 auction_core.wsgi
    image: "uni_auction_stage_${TAG}"
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    env_file:
      - .stage.env
    environment:
      - TAG=${TAG}
      - ENV=staging
    depends_on:
      - db_stage

volumes:
  uni_auction_stage_postgres_data:
