# Generated by Django 4.0.5 on 2022-06-07 22:15

import core.utils.defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default=core.utils.defaults.generate_guid, editable=False, max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('service_name', models.CharField(max_length=100)),
                ('secret', models.CharField(db_index=True, default=core.utils.defaults.generate_guid, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
