# Generated by Django 4.0.5 on 2022-06-05 14:26

import core.utils.defaults
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('ATTN', 'ATTN'), ('ADMIN', 'ADMIN'), ('BUYER', 'BUYER'), ('SELLER', 'SELLER')], max_length=100),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default=core.utils.defaults.generate_guid, editable=False, max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=10)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user_profile.credit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
