# Generated by Django 4.0.5 on 2022-06-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('ATTN', 'Attn'), ('ADMIN', 'Admin'), ('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=100),
        ),
    ]
