# Generated by Django 4.0.5 on 2022-06-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_bidtransaction_auction'),
        ('user_profile', '0007_profile_can_attend_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='bid_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.bidtransaction'),
        ),
    ]
