# Generated by Django 4.0.5 on 2022-06-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_credittransaction_bid_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10),
        ),
    ]
