# Generated by Django 4.0.5 on 2022-06-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_bidtransaction_auction'),
        ('user_profile', '0010_credittransaction_auction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='auction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.auction'),
        ),
    ]
