# Generated by Django 4.0.5 on 2022-06-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_alter_credittransaction_auction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credittransaction',
            old_name='auction_id',
            new_name='auction',
        ),
    ]
