name: Production Deployment

on:
  push:
    branches:
      - production

jobs:
  production_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Cloud [Production]
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSHK }}
          script: |
            cd ~/uni/auction_core
            git pull origin ${{ github.ref_name }}
            git checkout ${{ github.sha }}
            chmod +x entrypoint.sh
            chmod +x entrypoint-server.sh
            TAG=${{ github.sha }} docker compose -f "docker_compose_production.yml" up -d --build --remove-orphans
            docker compose -f "docker_compose_production.yml" ps
            docker compose -f "docker_compose_production.yml" logs
#            docker compose -f "docker_compose_production.yml" exec -T web_production python3 manage.py makemigrations
#            docker compose -f "docker_compose_production.yml" exec -T web_production python3 manage.py migrate
#            docker compose -f "docker_compose_production.yml" exec -T web_production python3 manage.py collectstatic --no-input
#            docker compose -f "docker_compose_production.yml" exec -T web_production python3 manage.py test
