name: Stage Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploying to Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSHK }}
          script: |
            cd ~/uni/auction_core
            git pull
            echo ${{ github.sha }}
            docker compose -f "docker-compose_stage.yml" -e TAG=${{ github.sha }} up -d --build
            docker compose -f "docker-compose_stage.yml" ps
            docker compose -f "docker-compose_stage.yml" exec -T web_stage python3 manage.py makemigrations
            docker compose -f "docker-compose_stage.yml" exec -T web_stage python3 manage.py migrate
            docker compose -f "docker-compose_stage.yml" exec -T web_stage python3 manage.py collectstatic --no-input
