name: Stage Deployment

on:
  push:
    branches:
      - master

jobs:
  stage_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Cloud [Staging]
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSHK }}
          script: |
            cd ~/uni/auction_core
            git pull origin ${{ github.ref_name }}
            echo ${{ github.sha }}
            git checkout ${{ github.sha }}
            TAG=${{ github.sha }} docker compose -f "docker-compose_stage.yml" up -d --build --remove-orphans
            docker compose -f "docker-compose_stage.yml" ps
            docker compose -f "docker-compose_stage.yml" exec -T web_stage python3 manage.py makemigrations
            docker compose -f "docker-compose_stage.yml" exec -T web_stage python3 manage.py migrate
            docker compose -f "docker-compose_stage.yml" exec -T web_stage python3 manage.py collectstatic --no-input
            docker compose -f "docker-compose_stage.yml" exec -T web_stage python3 manage.py test
